/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author Usuario
 */
public class catalogoDieta extends javax.swing.JFrame {

    /**
     * Creates new form catalogoDieta
     */
    public catalogoDieta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        PanelDesayuno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        txtDescripcion1 = new javax.swing.JTextField();
        lblFoto1 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        txtDescripcion2 = new javax.swing.JTextField();
        lblFoto2 = new javax.swing.JLabel();
        btnArriba = new javax.swing.JButton();
        btnAbajo = new javax.swing.JButton();
        PanelComida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion3 = new javax.swing.JTextField();
        lblFoto3 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        txtDescripcion4 = new javax.swing.JTextField();
        lblFoto4 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        txtDescripcion5 = new javax.swing.JTextField();
        lblFoto5 = new javax.swing.JLabel();
        btnArriba1 = new javax.swing.JButton();
        btnAbajo1 = new javax.swing.JButton();
        PanelColacion = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtDescripcion12 = new javax.swing.JTextField();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        txtDescripcion13 = new javax.swing.JTextField();
        jCheckBox17 = new javax.swing.JCheckBox();
        txtDescripcion14 = new javax.swing.JTextField();
        btnArriba4 = new javax.swing.JButton();
        btnAbajo4 = new javax.swing.JButton();
        PanelCena = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcion15 = new javax.swing.JTextField();
        lblFoto12 = new javax.swing.JLabel();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        txtDescripcion16 = new javax.swing.JTextField();
        lblFoto13 = new javax.swing.JLabel();
        jCheckBox20 = new javax.swing.JCheckBox();
        txtDescripcion17 = new javax.swing.JTextField();
        lblFoto14 = new javax.swing.JLabel();
        btnArriba5 = new javax.swing.JButton();
        btnAbajo5 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logochico.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(470, 470, 470))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Logo)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PanelDesayuno.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel4.setText("Desayuno");

        txtDescripcion.setEditable(false);

        lblFoto.setText("foto");

        txtDescripcion1.setEditable(false);

        lblFoto1.setText("foto");

        txtDescripcion2.setEditable(false);

        lblFoto2.setText("foto");

        btnArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/arriba.PNG"))); // NOI18N

        btnAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/abajo.PNG"))); // NOI18N

        javax.swing.GroupLayout PanelDesayunoLayout = new javax.swing.GroupLayout(PanelDesayuno);
        PanelDesayuno.setLayout(PanelDesayunoLayout);
        PanelDesayunoLayout.setHorizontalGroup(
            PanelDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesayunoLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelDesayunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDesayunoLayout.createSequentialGroup()
                        .addComponent(jCheckBox3)
                        .addGap(15, 15, 15)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDesayunoLayout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addGap(15, 15, 15)
                        .addComponent(txtDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDesayunoLayout.createSequentialGroup()
                        .addGroup(PanelDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDesayunoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnArriba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAbajo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDesayunoLayout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addGap(15, 15, 15)
                                .addComponent(txtDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelDesayunoLayout.setVerticalGroup(
            PanelDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDesayunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDesayunoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox3)))
                .addGap(18, 18, 18)
                .addGroup(PanelDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDesayunoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox4)))
                .addGap(18, 18, 18)
                .addGroup(PanelDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelDesayunoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox5)))
                .addGap(18, 18, 18)
                .addGroup(PanelDesayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArriba)
                    .addComponent(btnAbajo))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        PanelComida.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel5.setText("Comida");

        txtDescripcion3.setEditable(false);

        lblFoto3.setText("foto");

        txtDescripcion4.setEditable(false);

        lblFoto4.setText("foto");

        txtDescripcion5.setEditable(false);

        lblFoto5.setText("foto");

        btnArriba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/arriba.PNG"))); // NOI18N

        btnAbajo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/abajo.PNG"))); // NOI18N

        javax.swing.GroupLayout PanelComidaLayout = new javax.swing.GroupLayout(PanelComida);
        PanelComida.setLayout(PanelComidaLayout);
        PanelComidaLayout.setHorizontalGroup(
            PanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComidaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComidaLayout.createSequentialGroup()
                        .addComponent(jCheckBox6)
                        .addGap(15, 15, 15)
                        .addComponent(txtDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelComidaLayout.createSequentialGroup()
                        .addComponent(jCheckBox7)
                        .addGap(15, 15, 15)
                        .addComponent(txtDescripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelComidaLayout.createSequentialGroup()
                        .addGroup(PanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComidaLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnArriba1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAbajo1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelComidaLayout.createSequentialGroup()
                                .addComponent(jCheckBox8)
                                .addGap(15, 15, 15)
                                .addComponent(txtDescripcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PanelComidaLayout.setVerticalGroup(
            PanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelComidaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox6)))
                .addGap(18, 18, 18)
                .addGroup(PanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelComidaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox7)))
                .addGap(18, 18, 18)
                .addGroup(PanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelComidaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox8)))
                .addGap(18, 18, 18)
                .addGroup(PanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArriba1)
                    .addComponent(btnAbajo1))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        PanelColacion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel8.setText("Colación");

        txtDescripcion12.setEditable(false);

        txtDescripcion13.setEditable(false);

        txtDescripcion14.setEditable(false);

        btnArriba4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/arriba.PNG"))); // NOI18N

        btnAbajo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/abajo.PNG"))); // NOI18N

        javax.swing.GroupLayout PanelColacionLayout = new javax.swing.GroupLayout(PanelColacion);
        PanelColacion.setLayout(PanelColacionLayout);
        PanelColacionLayout.setHorizontalGroup(
            PanelColacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColacionLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelColacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelColacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColacionLayout.createSequentialGroup()
                        .addComponent(jCheckBox15)
                        .addGap(15, 15, 15)
                        .addComponent(txtDescripcion12, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelColacionLayout.createSequentialGroup()
                        .addComponent(jCheckBox16)
                        .addGap(15, 15, 15)
                        .addComponent(txtDescripcion13, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelColacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelColacionLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(btnArriba4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAbajo4))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelColacionLayout.createSequentialGroup()
                            .addComponent(jCheckBox17)
                            .addGap(15, 15, 15)
                            .addComponent(txtDescripcion14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        PanelColacionLayout.setVerticalGroup(
            PanelColacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelColacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelColacionLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox15)))
                .addGap(18, 18, 18)
                .addGroup(PanelColacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelColacionLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox16)))
                .addGap(18, 18, 18)
                .addGroup(PanelColacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion14, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelColacionLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox17)))
                .addGap(18, 18, 18)
                .addGroup(PanelColacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArriba4)
                    .addComponent(btnAbajo4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCena.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel9.setText("Cena");

        txtDescripcion15.setEditable(false);

        lblFoto12.setText("foto");

        txtDescripcion16.setEditable(false);

        lblFoto13.setText("foto");

        txtDescripcion17.setEditable(false);

        lblFoto14.setText("foto");

        btnArriba5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/arriba.PNG"))); // NOI18N

        btnAbajo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/abajo.PNG"))); // NOI18N

        btnCancelar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");

        btnAgregar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");

        javax.swing.GroupLayout PanelCenaLayout = new javax.swing.GroupLayout(PanelCena);
        PanelCena.setLayout(PanelCenaLayout);
        PanelCenaLayout.setHorizontalGroup(
            PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCenaLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelCenaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCenaLayout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addGroup(PanelCenaLayout.createSequentialGroup()
                        .addGroup(PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCenaLayout.createSequentialGroup()
                                .addComponent(jCheckBox18)
                                .addGap(15, 15, 15)
                                .addComponent(txtDescripcion15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFoto12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCenaLayout.createSequentialGroup()
                                .addComponent(jCheckBox19)
                                .addGap(15, 15, 15)
                                .addComponent(txtDescripcion16, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFoto13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCenaLayout.createSequentialGroup()
                                .addGroup(PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCenaLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(btnArriba5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAbajo5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCenaLayout.createSequentialGroup()
                                        .addComponent(jCheckBox20)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtDescripcion17, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFoto14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelCenaLayout.setVerticalGroup(
            PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCenaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion15, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCenaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox18)))
                .addGap(18, 18, 18)
                .addGroup(PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion16, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCenaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox19)))
                .addGap(18, 18, 18)
                .addGroup(PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion17, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCenaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCheckBox20)))
                .addGap(18, 18, 18)
                .addGroup(PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArriba5)
                    .addComponent(btnAbajo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAgregar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(PanelComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(PanelColacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(PanelCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelColacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalogoDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalogoDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalogoDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalogoDieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogoDieta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelCena;
    private javax.swing.JPanel PanelColacion;
    private javax.swing.JPanel PanelComida;
    private javax.swing.JPanel PanelDesayuno;
    private javax.swing.JButton btnAbajo;
    private javax.swing.JButton btnAbajo1;
    private javax.swing.JButton btnAbajo4;
    private javax.swing.JButton btnAbajo5;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnArriba;
    private javax.swing.JButton btnArriba1;
    private javax.swing.JButton btnArriba4;
    private javax.swing.JButton btnArriba5;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblFoto12;
    private javax.swing.JLabel lblFoto13;
    private javax.swing.JLabel lblFoto14;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblFoto3;
    private javax.swing.JLabel lblFoto4;
    private javax.swing.JLabel lblFoto5;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescripcion1;
    private javax.swing.JTextField txtDescripcion12;
    private javax.swing.JTextField txtDescripcion13;
    private javax.swing.JTextField txtDescripcion14;
    private javax.swing.JTextField txtDescripcion15;
    private javax.swing.JTextField txtDescripcion16;
    private javax.swing.JTextField txtDescripcion17;
    private javax.swing.JTextField txtDescripcion2;
    private javax.swing.JTextField txtDescripcion3;
    private javax.swing.JTextField txtDescripcion4;
    private javax.swing.JTextField txtDescripcion5;
    // End of variables declaration//GEN-END:variables
}
