/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import constantes.Constantes;
import dominio.Cena;
import dominio.Comida;
import dominio.Desayuno;
import dominio.Dieta;
import interfaces.IPersistenciaFachada;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import negocio.PersistenciaFachada;
import static sun.security.krb5.Confounder.bytes;

/**
 *
 * @author Usuario
 */
public class DietaDialog extends javax.swing.JFrame {

    byte[] myImgDesayuno;
    byte[] myImgComida;
    byte[] myImgCena;
    IPersistenciaFachada persistenciaFachada;
    int seleccion;

    /**
     * Creates new form agregarDieta
     *
     * @param seleccion
     * @throws java.sql.SQLException
     */
    public DietaDialog(int seleccion) throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        this.seleccion = seleccion;
        if (seleccion == Constantes.AGREGAR) {
            lblID.setVisible(false);
            txtBuscarIDDieta.setVisible(false);
            btnBuscarDieta.setVisible(false);
        }

        if (seleccion == Constantes.ACTUALIZAR) {
            setTitle("Actualizar Dieta");
            btnGuardar.setText("Actualizar");
        }
        this.persistenciaFachada = PersistenciaFachada.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNombreNutriologo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreDieta = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtBuscarIDDieta = new javax.swing.JTextField();
        btnBuscarDieta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        comboDia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNombreDesayuno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombreComida = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtColacionComida = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNombreCena = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        imgCena = new javax.swing.JLabel();
        imgDesayuno = new javax.swing.JLabel();
        imgComida = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNumCaloriasDesayuno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAcompañanteDesayuno = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIngredientesDesayuno = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtIngredientesComida = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAcompañanteComida = new javax.swing.JTextArea();
        txtColacionDesayuno = new javax.swing.JTextField();
        txtNumCaloriasComida = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtIngredientesCena = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAcompañanteCena = new javax.swing.JTextArea();
        txtNumCaloriasCena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Dieta");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logochico.PNG"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Nutriólogo:");

        lblNombreNutriologo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNombreNutriologo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreNutriologo1.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(6, 6, Short.MAX_VALUE)
                .addComponent(lblNombreNutriologo1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Logo)
                .addGap(431, 431, 431))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNombreNutriologo1)
                                .addGap(44, 44, 44))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel1.setText("Nombre");

        txtNombreDieta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblID.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        lblID.setText("ID:");

        txtBuscarIDDieta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnBuscarDieta.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnBuscarDieta.setText("Buscar");
        btnBuscarDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDietaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarIDDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarDieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID)
                    .addComponent(txtBuscarIDDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDieta))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        txtNombreDieta.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        fechaFinal.setEnabled(false);

        fechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaInicioPropertyChange(evt);
            }
        });

        comboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día 1", "Día 2", "Día 3", "Día 4", "Día 5", "Día 6", "Día 7" }));
        comboDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDiaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel2.setText("Desayuno");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel4.setText("Ingredientes");

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel5.setText("Acompañantes");

        jLabel6.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel6.setText("Número de Calorías");

        jLabel13.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel13.setText("Comida");

        jLabel14.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel14.setText("Nombre");

        jLabel15.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel15.setText("Ingredientes");

        jLabel16.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel16.setText("Acompañantes");

        jLabel17.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel17.setText("Colación");

        jLabel19.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel19.setText("Cena");

        jLabel20.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel20.setText("Nombre");

        jLabel22.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel22.setText("Ingredientes");

        jLabel23.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel23.setText("Acompañantes");

        btnCancelar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        imgCena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imgIcon.png"))); // NOI18N
        imgCena.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        imgCena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgCena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgCenaMousePressed(evt);
            }
        });

        imgDesayuno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imgIcon.png"))); // NOI18N
        imgDesayuno.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        imgDesayuno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgDesayuno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgDesayunoMousePressed(evt);
            }
        });

        imgComida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imgIcon.png"))); // NOI18N
        imgComida.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        imgComida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgComidaMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("-");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel8.setText("Colación");

        jLabel11.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel11.setText("Número de Calorías");

        jLabel12.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel12.setText("Número de Calorías");

        txtAcompañanteDesayuno.setColumns(20);
        txtAcompañanteDesayuno.setRows(5);
        jScrollPane1.setViewportView(txtAcompañanteDesayuno);

        txtIngredientesDesayuno.setColumns(20);
        txtIngredientesDesayuno.setRows(5);
        jScrollPane2.setViewportView(txtIngredientesDesayuno);

        txtIngredientesComida.setColumns(20);
        txtIngredientesComida.setRows(5);
        jScrollPane3.setViewportView(txtIngredientesComida);

        txtAcompañanteComida.setColumns(20);
        txtAcompañanteComida.setRows(5);
        jScrollPane4.setViewportView(txtAcompañanteComida);

        txtIngredientesCena.setColumns(20);
        txtIngredientesCena.setRows(5);
        jScrollPane5.setViewportView(txtIngredientesCena);

        txtAcompañanteCena.setColumns(20);
        txtAcompañanteCena.setRows(5);
        jScrollPane6.setViewportView(txtAcompañanteCena);

        txtNumCaloriasCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCaloriasCenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(484, 484, 484)
                        .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(85, 85, 85))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtNombreDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(imgDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNumCaloriasDesayuno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtColacionDesayuno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)
                                            .addComponent(txtNombreComida, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imgComida, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNumCaloriasComida, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtColacionComida, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(txtNumCaloriasCena))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(txtNombreCena, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel22)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(imgCena, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(36, 36, 36))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel13)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreComida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel2)
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombreDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(imgComida, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(imgDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtColacionDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addGap(3, 3, 3)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtColacionComida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumCaloriasCena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(imgCena, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreCena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 53, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumCaloriasDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtNumCaloriasComida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDiaActionPerformed

    private void imgDesayunoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgDesayunoMousePressed
        myImgDesayuno = insertarImagen(imgDesayuno);
    }//GEN-LAST:event_imgDesayunoMousePressed

    private void imgComidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgComidaMousePressed
        myImgComida = insertarImagen(imgComida);
    }//GEN-LAST:event_imgComidaMousePressed

    private void imgCenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCenaMousePressed
        myImgCena = insertarImagen(imgCena);
    }//GEN-LAST:event_imgCenaMousePressed

    private void fechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaInicioPropertyChange

        try {
            Date fechaSeleccionada = fechaInicio.getDate();
            // Calcular una semana después de la fecha seleccionada
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(fechaSeleccionada);
            calendar.add(Calendar.WEEK_OF_YEAR, 1);

            fechaFinal.setDate(calendar.getTime());
        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_fechaInicioPropertyChange

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validar()) {
            String nombreDieta = txtNombreDieta.getText();
            Date myFechaInicio = fechaInicio.getDate();
            Date myFechaFinal = fechaFinal.getDate();

            int diaSemana = Integer.parseInt(comboDia.getSelectedItem().toString().substring(4));

            String nombreDesayuno = txtNombreDesayuno.getText();
            String nombreComida = txtNombreComida.getText();
            String nombreCena = txtNombreCena.getText();

            String ingredientesDesayuno = txtIngredientesDesayuno.getText();
            String ingredientesComida = txtIngredientesComida.getText();
            String ingredientesCena = txtIngredientesCena.getText();

            String acompañanteDesayuno = txtAcompañanteDesayuno.getText();
            String acompañanteComida = txtAcompañanteComida.getText();
            String acompañanteCena = txtAcompañanteCena.getText();

            String colacionDesayuno = txtColacionDesayuno.getText();
            String colacionComida = txtColacionComida.getText();

            Desayuno desayuno = new Desayuno(nombreDesayuno, ingredientesDesayuno, acompañanteDesayuno,
                    Integer.parseInt(txtNumCaloriasDesayuno.getText()), myImgDesayuno, colacionDesayuno);

            Comida comida = new Comida(nombreComida, ingredientesComida, acompañanteComida,
                    Integer.parseInt(txtNumCaloriasComida.getText()), myImgComida, colacionComida);

            Cena cena = new Cena(nombreCena, ingredientesCena, acompañanteCena,
                    Integer.parseInt(txtNumCaloriasCena.getText()), myImgCena);

            Dieta dieta = new Dieta(nombreDieta, myFechaInicio, myFechaFinal, diaSemana, desayuno, comida, cena);

            if (seleccion == Constantes.AGREGAR) {
                if (persistenciaFachada.registrarDieta(dieta)) {
                    JOptionPane.showMessageDialog(null, "Dieta guardada con éxito.",
                            "Dieta", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado.",
                            "Dieta", JOptionPane.INFORMATION_MESSAGE);
                }
                return;
            }

            if (seleccion == Constantes.ACTUALIZAR) {
                int id = validarCadena(txtBuscarIDDieta.getText()) ? Integer.parseInt(txtBuscarIDDieta.getText()) : -1;

                if (id == -1) {
                    JOptionPane.showMessageDialog(null, "El ID no es válido", "Dieta", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                Dieta dietaEncontrada = persistenciaFachada.buscarDietaPorID(id);

                dieta.getDesayuno().setId(dietaEncontrada.getDesayuno().getId());
                dieta.getComida().setId(dietaEncontrada.getComida().getId());
                dieta.getCena().setId(dietaEncontrada.getCena().getId());

                if (persistenciaFachada.actualizarDieta(id, dieta)) {
                    JOptionPane.showMessageDialog(null, "Dieta actualizada con éxito.",
                            "Dieta", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Ocurrió un error inesperado.",
                            "Dieta", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    public boolean validar() {

        if (txtAcompañanteCena.getText().equals("") && txtAcompañanteComida.getText().equals("") && txtAcompañanteDesayuno.getText().equals("")
                && txtColacionComida.getText().equals("") && txtColacionDesayuno.getText().equals("")
                && txtIngredientesCena.getText().equals("") && txtIngredientesComida.getText().equals("") && txtIngredientesDesayuno.getText().equals("")
                && txtNombreComida.getText().equals("") && txtNombreDesayuno.getText().equals("") && txtNombreCena.getText().equals("") && txtNombreDieta.getText().equals("")
                && txtNumCaloriasCena.getText().equals("") && txtNumCaloriasDesayuno.getText().equals("") && txtNumCaloriasComida.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Campos vacios. Ingrese la información requerida.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;

        }
        if (txtAcompañanteCena.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de acompañante de cena vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtAcompañanteCena.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de acompañante de cena.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtAcompañanteComida.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de acompañante de comida vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtAcompañanteComida.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de acompañante de comida.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtAcompañanteDesayuno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de acompañante de desayuno vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtAcompañanteDesayuno.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de acompañante de desayuno.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }

        if (txtColacionComida.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de colaciones de comida vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtColacionComida.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de colacion de comida.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtColacionDesayuno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de colaciones de desayuno vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtColacionDesayuno.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de colacion de desayuno.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtIngredientesCena.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de ingredientes de cena vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtIngredientesCena.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de ingredientes de cena.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtIngredientesComida.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de ingredientes de comida vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtIngredientesComida.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de ingredientes de comida.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtIngredientesDesayuno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de ingredientes de desayuno vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtIngredientesDesayuno.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de ingredientes de desayuno.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtNombreComida.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de nombre de comida vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtNombreComida.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de nombre de comida.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtNombreDesayuno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de nombre de desayuno vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtNombreDesayuno.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de nombre de desayuno.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtNombreDieta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de nombre de dieta vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtNombreDieta.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de nombre de dieta.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtNombreCena.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de nombre de cena vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarNombre(txtNombreCena.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de nombre de cena.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtNumCaloriasCena.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de calorias de cena vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarCadena(txtNumCaloriasCena.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de calorias de cena.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtNumCaloriasComida.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de calorias de comida vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarCadena(txtNumCaloriasComida.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de calorias de comida.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (txtNumCaloriasDesayuno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo de calorias de desayuno vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validarCadena(txtNumCaloriasDesayuno.getText())) {
            JOptionPane.showMessageDialog(null, "Valor invalido en el campo de calorias de desayuno.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (fechaInicio.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Campo de fecha de inicio de dieta vacio.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (myImgCena == null) {
            JOptionPane.showMessageDialog(null, "Suba una foto del platillo de cena.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (myImgComida == null) {
            JOptionPane.showMessageDialog(null, "Suba una foto del platillo de comida.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (myImgDesayuno == null) {
            JOptionPane.showMessageDialog(null, "Suba una foto del platillo de desayuno.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validateByteArrayElement(myImgCena)) {
            JOptionPane.showMessageDialog(null, "Suba una foto de la cena con el tamaño menor a 4GB", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validateByteArrayElement(myImgComida)) {
            JOptionPane.showMessageDialog(null, "Suba una foto de la comida con el tamaño menor a 4GB", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (!validateByteArrayElement(myImgDesayuno)) {
            JOptionPane.showMessageDialog(null, "Suba una foto del desayuno con el tamaño menor a 4GB", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }

    public boolean validateByteArrayElement(byte[] byteArray) {
        long maxSize = 4000000;
        int index = 0;
        return (byteArray[index] & 0xFF) <= maxSize;
    }

    public boolean validarCadena(String calorias) {
        if (calorias.length() < 1 || calorias.length() > 5) {
            return false;
        }
        for (int i = 0; i < calorias.length(); i++) {
            if (!Character.isDigit(calorias.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    public boolean validarNombre(String nombre) {
        String regex = "^[a-zA-ZñÑáéíóúÁÉÍÓÚ0-9\\s]+$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(nombre);
        return matcher.matches();
    }

    private void txtNumCaloriasCenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCaloriasCenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCaloriasCenaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDietaActionPerformed
        int id = validarCadena(txtBuscarIDDieta.getText()) ? Integer.parseInt(txtBuscarIDDieta.getText()) : -1;

        if (id == -1) {
            JOptionPane.showMessageDialog(null, "El ID no es válido", "Dieta", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Dieta dieta = persistenciaFachada.buscarDietaPorID(id);
        if (dieta != null) {
            llenarCamposDeActualizarDieta(dieta);
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró la dieta.", "Dieta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarDietaActionPerformed

    public void llenarCamposDeActualizarDieta(Dieta dieta) {
        txtNombreDieta.setText(dieta.getNombreDieta());
        fechaInicio.setDate(dieta.getFechaInicio());
        fechaFinal.setDate(dieta.getFechaFinal());
        comboDia.setSelectedItem("Día " + dieta.getDiaSemana());

        // Imagenes ...
        myImgDesayuno = dieta.getDesayuno().getFoto();
        myImgComida = dieta.getComida().getFoto();
        myImgCena = dieta.getCena().getFoto();

        escalarImagen(myImgDesayuno, imgDesayuno);
        escalarImagen(myImgComida, imgComida);
        escalarImagen(myImgCena, imgCena);

        // Desayuno ...
        txtNombreDesayuno.setText(dieta.getDesayuno().getNombre());
        txtIngredientesDesayuno.setText(dieta.getDesayuno().getIngredientes());
        txtAcompañanteDesayuno.setText(dieta.getDesayuno().getAcompanante());
        txtColacionDesayuno.setText(dieta.getDesayuno().getColacion());
        txtNumCaloriasDesayuno.setText(String.valueOf(dieta.getDesayuno().getNumCalorias()));

        // Comida ...
        txtNombreComida.setText(dieta.getComida().getNombre());
        txtIngredientesComida.setText(dieta.getComida().getIngredientes());
        txtAcompañanteComida.setText(dieta.getComida().getAcompanante());
        txtColacionComida.setText(dieta.getComida().getColacion());
        txtNumCaloriasComida.setText(String.valueOf(dieta.getComida().getNumCalorias()));

        // Cena ...
        txtNombreCena.setText(dieta.getCena().getNombre());
        txtIngredientesCena.setText(dieta.getCena().getIngredientes());
        txtAcompañanteCena.setText(dieta.getCena().getAcompanante());
        txtNumCaloriasCena.setText(String.valueOf(dieta.getCena().getNumCalorias()));
    }

    public ImageIcon bytesToImage(byte[] bytesImage) {
        try {
            InputStream inputStream = new ByteArrayInputStream(bytesImage);
            BufferedImage bufferedImage = ImageIO.read(inputStream);
            return new ImageIcon(bufferedImage);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    public void escalarImagen(byte[] imagenBytes, JLabel label) {

        BufferedImage image = null;
        File tempFile = null;
        
        try {
            tempFile = File.createTempFile("temp", ".jpg");
        } catch (IOException ex) {
            System.out.println("Error en: "+ex);
        }
        try (FileOutputStream fos = new FileOutputStream(tempFile)) {
            fos.write(imagenBytes);
        } catch (Exception ex) {
            System.out.println("error: "+ex);
        } 

        try {
            image = ImageIO.read(tempFile);
        } catch (IOException ex) {
            Logger.getLogger(DietaDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image scaledImage = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon = new ImageIcon(scaledImage);
        label.setIcon(icon);
    }

    public byte[] insertarImagen(JLabel label) {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            BufferedImage image = null;
            try {
                image = ImageIO.read(new File(selectedFile.getAbsolutePath()));
            } catch (IOException ex) {
                Logger.getLogger(DietaDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image scaledImage = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(scaledImage);
            label.setIcon(icon);

            try {
                return iconToBytes(new ImageIcon(selectedFile.getAbsolutePath()));
            } catch (IOException ex) {
                System.out.println(ex);
            }
        }
        return null;
    }

    public static byte[] iconToBytes(Icon icon) throws IOException {
        BufferedImage bufferedImage = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
        icon.paintIcon(null, bufferedImage.getGraphics(), 0, 0);
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        ImageIO.write(bufferedImage, "jpg", outputStream);
        return outputStream.toByteArray();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnBuscarDieta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboDia;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel imgCena;
    private javax.swing.JLabel imgComida;
    private javax.swing.JLabel imgDesayuno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombreNutriologo1;
    private javax.swing.JTextArea txtAcompañanteCena;
    private javax.swing.JTextArea txtAcompañanteComida;
    private javax.swing.JTextArea txtAcompañanteDesayuno;
    private javax.swing.JTextField txtBuscarIDDieta;
    private javax.swing.JTextField txtColacionComida;
    private javax.swing.JTextField txtColacionDesayuno;
    private javax.swing.JTextArea txtIngredientesCena;
    private javax.swing.JTextArea txtIngredientesComida;
    private javax.swing.JTextArea txtIngredientesDesayuno;
    private javax.swing.JTextField txtNombreCena;
    private javax.swing.JTextField txtNombreComida;
    private javax.swing.JTextField txtNombreDesayuno;
    private javax.swing.JTextField txtNombreDieta;
    private javax.swing.JTextField txtNumCaloriasCena;
    private javax.swing.JTextField txtNumCaloriasComida;
    private javax.swing.JTextField txtNumCaloriasDesayuno;
    // End of variables declaration//GEN-END:variables
}
