/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import constantes.Constantes;
import dominio.Paciente;
import dominio.Persona;

/**
 *
 * @author ldoar
 */
public class FrInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrInicio
     */
    public FrInicio() {
        initComponents();
        setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemAgregarDieta = new javax.swing.JMenu();
        itemAgregarPaciente = new javax.swing.JMenuItem();
        agregarDieta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemActualiarPaciente = new javax.swing.JMenuItem();
        itemActualizarDieta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemMostrarCatalogo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(783, 642));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(867, 618));
        jPanel2.setRequestFocusEnabled(false);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/LogoG_sinFondo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        itemAgregarDieta.setText("Agregar");
        itemAgregarDieta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        itemAgregarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemAgregarPaciente.setText("Agregar paciente");
        itemAgregarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarPacienteActionPerformed(evt);
            }
        });
        itemAgregarDieta.add(itemAgregarPaciente);

        agregarDieta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        agregarDieta.setText("Agregar dieta");
        agregarDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDietaActionPerformed(evt);
            }
        });
        itemAgregarDieta.add(agregarDieta);

        jMenuBar1.add(itemAgregarDieta);

        jMenu2.setText("Actualizar");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        itemActualiarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemActualiarPaciente.setText("Actualizar paciente");
        itemActualiarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualiarPacienteActionPerformed(evt);
            }
        });
        jMenu2.add(itemActualiarPaciente);

        itemActualizarDieta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemActualizarDieta.setText("Actualizar dieta");
        itemActualizarDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarDietaActionPerformed(evt);
            }
        });
        jMenu2.add(itemActualizarDieta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Catalogo");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        itemMostrarCatalogo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemMostrarCatalogo.setText("Mostrar catalogo");
        itemMostrarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarCatalogoActionPerformed(evt);
            }
        });
        jMenu3.add(itemMostrarCatalogo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void itemAgregarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarPacienteActionPerformed
        new PersonaDialog(new Persona(), new Paciente(), Constantes.AGREGAR);
    }//GEN-LAST:event_itemAgregarPacienteActionPerformed

    private void agregarDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDietaActionPerformed
        new DietaDialog(Constantes.AGREGAR).setVisible(true);
    }//GEN-LAST:event_agregarDietaActionPerformed

    private void itemActualiarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualiarPacienteActionPerformed
        new PersonaDialog(new Persona(), new Paciente(), Constantes.ACTUALIZAR);
    }//GEN-LAST:event_itemActualiarPacienteActionPerformed

    private void itemActualizarDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarDietaActionPerformed
        new DietaDialog(Constantes.ACTUALIZAR).setVisible(true);
    }//GEN-LAST:event_itemActualizarDietaActionPerformed

    private void itemMostrarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarCatalogoActionPerformed
        new CatalogoDieta(new Paciente(), Constantes.AGREGAR).setVisible(true);
    }//GEN-LAST:event_itemMostrarCatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JMenuItem agregarDieta;
    private javax.swing.JMenuItem itemActualiarPaciente;
    private javax.swing.JMenuItem itemActualizarDieta;
    private javax.swing.JMenu itemAgregarDieta;
    private javax.swing.JMenuItem itemAgregarPaciente;
    private javax.swing.JMenuItem itemMostrarCatalogo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
